spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

#logging:
#  level:
#    org:
#      springframework:
#        web: debug