spring:
  application:
    name: spring-3-graghql

  graphql:
    graphiql:
      enabled: true
#spring.graphql.schema.locations=classpath*:graphql/**/
    websocket:
      path: /subscriptions

#  threads:
#    virtual:
#      enabled: true
